networks:
  default:

services:
  mysql-db:
    # NOTE: Uncomment the line below if you are using Mac with m1/m2 chip
    # platform: linux/x86_64
    container_name:  mysql
    image: mysql:5.7
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - path: ./.env
        required: true # defaul
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSOWRD}
    ports:
      - 3336:3306
    expose:
      - 3336
    volumes:
      - mysql-volume:/var/lib/mysql:rw
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

  nestjs-pvp-app:
    container_name: nestjs-pvp-app
    depends_on:
      - mysql-db
    build:
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 3007:3007
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - default
    command: bash -c "npm install && npm run start:prod"

volumes: 
  mysql-volume: